# CMS Data Preparation

In this notebook, we will prepare the data for the CMS by transforming it into the required format and structure.
## Table of Contents
### [Locations Table](#locations)
- **[Country Boundaries (OSM)](#country-boundaries)**
- **[HydroBASINS](#hydro)**

## Setup

### Library import

In [1]:
import os

import geopandas as gpd

### Variables

In [2]:
DATA_PATH = "../data/processed"

### Utils

In [3]:
def create_sql_insert_queries(df, table_name):
    """
    Create SQL INSERT queries from a DataFrame.
    """
    queries = []
    for _, row in df.iterrows():
        columns = ", ".join([f'"{col}"' for col in df.columns])
        values = ", ".join([f"'{str(value)}'" for value in row])
        query = f"INSERT INTO {table_name} ({columns}) VALUES ({values});"
        queries.append(query)
    return queries

<a id='locations'></a>
## Locations

<a id='country-boundaries'></a>
### Country Boundaries (OSM)

**Read data**

In [7]:
gdf_countries = gpd.read_file(os.path.join(DATA_PATH, "countries_sahel.geojson"))
gdf_countries.head()

,name,bbox,ISO3,geometry
0,Senegal,"{ ""bbox"": [ -17.749868599999999, 12.2402663999...",SEN,"POLYGON ((-17.74987 14.74329, -17.74984 14.741..."
1,Mauritania,"{ ""bbox"": [ -17.238095900000001, 14.7209909, -...",MRT,"POLYGON ((-17.2381 20.66622, -17.23676 20.6625..."
2,Mali,"{ ""bbox"": [ -12.2402835, 10.147811000000001, 4...",MLI,"POLYGON ((-12.24028 14.76472, -12.23971 14.762..."
3,Burkina Faso,"{ ""bbox"": [ -5.5132070000000004, 9.41047179999...",BFA,"POLYGON ((-5.51321 10.43079, -5.51319 10.43066..."
4,Niger,"{ ""bbox"": [ 0.16896530000000001, 11.6936070999...",NER,"POLYGON ((0.16897 14.52207, 0.17333 14.50556, ..."

**Transform data**

In [8]:
gdf_countries.rename(columns={"ISO3": "code"}, inplace=True)
gdf_countries["type"] = "ADMIN_REGION"
gdf_countries = gdf_countries[["name", "code", "type", "bbox", "geometry"]]
gdf_countries.head()

,name,code,type,bbox,geometry
0,Senegal,SEN,ADMIN_REGION,"{ ""bbox"": [ -17.749868599999999, 12.2402663999...","POLYGON ((-17.74987 14.74329, -17.74984 14.741..."
1,Mauritania,MRT,ADMIN_REGION,"{ ""bbox"": [ -17.238095900000001, 14.7209909, -...","POLYGON ((-17.2381 20.66622, -17.23676 20.6625..."
2,Mali,MLI,ADMIN_REGION,"{ ""bbox"": [ -12.2402835, 10.147811000000001, 4...","POLYGON ((-12.24028 14.76472, -12.23971 14.762..."
3,Burkina Faso,BFA,ADMIN_REGION,"{ ""bbox"": [ -5.5132070000000004, 9.41047179999...","POLYGON ((-5.51321 10.43079, -5.51319 10.43066..."
4,Niger,NER,ADMIN_REGION,"{ ""bbox"": [ 0.16896530000000001, 11.6936070999...","POLYGON ((0.16897 14.52207, 0.17333 14.50556, ..."

**Save data**

CSV

In [13]:
gdf_countries.to_csv(os.path.join(DATA_PATH, "countries_sahel.csv"), index=False)

GeoJSON

In [9]:
gdf_countries.to_file(os.path.join(DATA_PATH, "countries_sahel_db.geojson"), driver="GeoJSON")

**Insert data to database**

In [15]:
# Example usage:
sql_queries = create_sql_insert_queries(gdf_countries, "admin_regions")
for q in sql_queries[:3]:
    print(q)

INSERT INTO admin_regions ("name", "code", "type", "bbox", "geometry") VALUES ('Senegal', 'SEN', 'ADMIN_REGION', '{ "bbox": [ -17.749868599999999, 12.240266399999999, -11.3459503, 16.691971200000001 ] }', 'POLYGON ((-17.7498686 14.7432872, -17.7498419 14.7410488, -17.7497395 14.7366653, -17.7495388 14.732285, -17.74924 14.72791, -17.7488433 14.7235424, -17.7483488 14.7191842, -17.7477567 14.7148376, -17.7470673 14.7105046, -17.7467065 14.7083864, -17.7462811 14.7061872, -17.7453983 14.7018875, -17.7444194 14.6976076, -17.7433448 14.6933496, -17.740968 14.68537, -17.7408214 14.6849433, -17.7401624 14.6828349, -17.7394174 14.6805421, -17.7387155 14.6784609, -17.738061 14.6765893, -17.7373197 14.6745422, -17.7364645 14.672261, -17.7356693 14.6702094, -17.7349314 14.668367, -17.7340915 14.6663353, -17.7331447 14.6641152, -17.7322576 14.6620974, -17.7314356 14.660283, -17.7305066 14.658291, -17.7294647 14.6561203, -17.7284335 14.6540345, -17.7245146 14.6462676, -17.7223453 14.6424251, -17.7212596 14.6405499, -17.7200905 14.6386296, -17.7177513 14.6348828, -17.7153287 14.6311866, -17.712824 14.6275427, -17.7102384 14.6239529, -17.707573 14.6204188, -17.7048292 14.6169421, -17.7020082 14.6135245, -17.7006019 14.6118576, -17.6977055 14.6086404, -17.6973519 14.6082455, -17.6924167 14.6018463, -17.6870463 14.5948779, -17.681676 14.5879096, -17.6763056 14.5809412, -17.6709352 14.5739729, -17.6655649 14.5670045, -17.6601945 14.5600362, -17.6548242 14.5530678, -17.6499054 14.5466854, -17.6492251 14.5457754, -17.6480172 14.5438146, -17.6461751 14.5410356, -17.6436714 14.5373917, -17.6410869 14.5338018, -17.6384226 14.5302676, -17.6356799 14.5267909, -17.6328601 14.5233733, -17.6314542 14.5217062, -17.6299645 14.5200163, -17.6269945 14.5167217, -17.6239515 14.5134909, -17.620837 14.5103255, -17.6176525 14.507227, -17.6143994 14.5041969, -17.6110793 14.5012366, -17.6076938 14.4983475, -17.606008 14.4969398, -17.6042446 14.495531, -17.6007331 14.4927884, -17.5971612 14.490121, -17.5935305 14.4875302, -17.5898427 14.4850171, -17.5860996 14.4825829, -17.582303 14.4802287, -17.5784547 14.4779558, -17.5765381 14.4768512, -17.5745565 14.4757651, -17.5706102 14.4736578, -17.5666178 14.4716348, -17.5625811 14.469697, -17.558502 14.4678455, -17.5543825 14.466081, -17.5502246 14.4644044, -17.5460302 14.4628165, -17.5439391 14.4620502, -17.5396113 14.4606209, -17.5391996 14.4605024, -17.5365294 14.459586, -17.534302 14.4588493, -17.5333104 14.4585336, -17.5313246 14.4579229, -17.5290439 14.4572461, -17.5261548 14.4563127, -17.5181856 14.45408, -17.5138147 14.4530387, -17.5094215 14.4520905, -17.5050082 14.4512359, -17.5028048 14.4508333, -17.5005769 14.4504751, -17.4961296 14.4498087, -17.4916684 14.4492369, -17.4871956 14.44876, -17.4827131 14.4483782, -17.4782232 14.4480916, -17.473728 14.4479006, -17.4692295 14.447805, -17.4669797 14.4477811, -17.4655184 14.4477966, -17.4620185 14.4472721, -17.4575574 14.4467003, -17.4530846 14.4462234, -17.4486022 14.4458416, -17.4441123 14.4455551, -17.4396171 14.445364, -17.4351187 14.4452684, -17.432869 14.4452445, -17.4306192 14.4452684, -17.4261208 14.445364, -17.4216256 14.4455551, -17.4171358 14.4458416, -17.4126534 14.4462234, -17.4081806 14.4467003, -17.4037195 14.4472721, -17.3992722 14.4479386, -17.3970443 14.4482968, -17.3941747 14.4488306, -17.3884362 14.4499802, -17.3827334 14.4512881, -17.377071 14.4527531, -17.3742504 14.4535248, -17.3731545 14.453841, -17.3716522 14.4542867, -17.3686547 14.4552003, -17.3656718 14.4561581, -17.3627042 14.4571601, -17.3612092 14.4576774, -17.3591182 14.4584438, -17.3549239 14.4600316, -17.350766 14.4617082, -17.3466466 14.4634727, -17.3425676 14.4653242, -17.338531 14.467262, -17.3345387 14.469285, -17.3305925 14.4713924, -17.3286109 14.4724784, -17.3266943 14.473583, -17.3261698 14.4738928, -17.3248488 14.4743769, -17.3206542 14.4759648, -17.3182157 14.476948, -17.3172465 14.4752131, -17.3159598 14.4729782, -17.314424 14.4704733, -17.3113209 14.4655747, -17.3080753 14.4607648, -17.3046897 14.4560473, -17.3029624 14.4537122, -17.2969315 14.4458003, -17.296 14.4445972, -17.2941187 14.4422048, -17.2922009 14.4398402, -17.2902469 14.4375038, -17.2892839 14.4363693, -17.287795 14.4346796, -17.2856647 14.4323156, -17.2853524 14.4314213, -17.2846192 14.4293935, -17.28381 14.4273022, -17.2821759 14.4232169, -17.2804507 14.4191673, -17.2786354 14.4151553, -17.2767308 14.4111829, -17.2747378 14.4072518, -17.2717 14.4017038, -17.2693957 14.3977948, -17.2690334 14.3971795, -17.2681991 14.3956946, -17.2670946 14.3937785, -17.2655697 14.3911996, -17.2653471 14.3908255, -17.2650077 14.3902579, -17.2631973 14.387117, -17.2625792 14.3860597, -17.2608333 14.3832234, -17.2589926 14.3804446, -17.2564908 14.3768005, -17.2539081 14.3732106, -17.2512458 14.3696764, -17.2485051 14.3661996, -17.2456873 14.3627819, -17.2442822 14.3611145, -17.2425582 14.359164, -17.2408676 14.3570151, -17.239736 14.3555901, -17.2338706 14.3483388, -17.2328683 14.3471193, -17.2308444 14.3446955, -17.2298456 14.3435177, -17.2283574 14.3418281, -17.2255174 14.338675, -17.2249304 14.337859, -17.2222685 14.3343248, -17.2195282 14.330848, -17.2167109 14.3274302, -17.2153059 14.3257627, -17.2138179 14.3240732, -17.2108505 14.3207785, -17.2078103 14.3175476, -17.2046985 14.3143821, -17.2015168 14.3112835, -17.1982665 14.3082533, -17.1949494 14.305293, -17.1915669 14.3024038, -17.1898823 14.3009958, -17.1885118 14.2998945, -17.1857979 14.2977517, -17.1830472 14.2956539, -17.1802605 14.2936019, -17.1774385 14.2915961, -17.1745822 14.2896373, -17.1716923 14.2877258, -17.1687697 14.2858624, -17.1673004 14.2849427, -17.1581608 14.2793281, -17.1564487 14.2782988, -17.1530043 14.2762731, -17.151292 14.2752879, -17.1493124 14.274202, -17.1453697 14.2720946, -17.1413808 14.2700715, -17.1373477 14.2681337, -17.1358243 14.2674415, -17.1357524 14.2669032, -17.1350343 14.2623453, -17.1346563 14.2601136, -17.1341904 14.2577136, -17.1332168 14.2530114, -17.1321284 14.2483332, -17.1309259 14.2436816, -17.1302963 14.2413628, -17.1277332 14.2323592, -17.1271689 14.2304503, -17.1260018 14.2266438, -17.1247579 14.2228606, -17.1234376 14.2191021, -17.1227731 14.2172685, -17.1219649 14.2151778, -17.1203324 14.2110924, -17.1186089 14.2070427, -17.1167953 14.2030306, -17.1148926 14.1990581, -17.1129015 14.195127, -17.1108231 14.1912391, -17.1086583 14.1873965, -17.1075742 14.18552, -17.1064081 14.1836007, -17.1040737 14.1798538, -17.1016562 14.1761574, -17.0991567 14.1725133, -17.0965764 14.1689232, -17.0939165 14.1653889, -17.0911783 14.161912, -17.0883631 14.1584942, -17.0869589 14.1568264, -17.0854722 14.1551371, -17.0825071 14.1518423, -17.0794691 14.1486114, -17.0763597 14.1454459, -17.0731803 14.1423472, -17.0699326 14.139317, -17.0665653 14.136221, -17.0653288 14.1317457, -17.0640679 14.127537, -17.0627132 14.1233562, -17.0612654 14.1192052, -17.0605329 14.1171764, -17.0597252 14.115086, -17.0580934 14.1110005, -17.0563707 14.1069508, -17.054558 14.1029387, -17.0526561 14.0989661, -17.0506659 14.0950349, -17.0485884 14.091147, -17.0464245 14.0873043, -17.0453408 14.0854276, -17.0441754 14.0835085, -17.0418421 14.0797615, -17.0394256 14.0760651, -17.0369272 14.072421, -17.034348 14.0688309, -17.0316893 14.0652965, -17.0289523 14.0618196, -17.0261384 14.0584018, -17.0247346 14.0567337, -17.0232488 14.0550446, -17.020285 14.0517498, -17.0172483 14.0485188, -17.0141403 14.0453532, -17.0109623 14.0422545, -17.0091799 14.0405907, -17.0075618 14.0385357, -17.0047588 14.0351314, -17.0033607 14.0334699, -17.0021392 14.0320758, -16.999716 14.0293604, -16.9972435 14.0266878, -16.9947223 14.0240589, -16.9921533 14.0214744, -16.9895374 14.0189353, -16.9868753 14.0164423, -16.9841681 14.0139963, -16.9828046 14.0127863, -16.9797613 14.0101336, -16.9793256 14.0096491, -16.9768421 14.0070063, -16.9767372 14.0059696, -16.9760184 14.0004386, -16.9735612 13.9849778, -16.9699463 13.9273344, -16.9695288 13.9225511, -16.9684605 13.9130091, -16.9678097 13.9082505, -16.9664191 13.8996519, -16.9662646 13.8987245, -16.9659466 13.896871, -16.9657909 13.8959872, -16.965414 13.8940314, -16.965763 13.890727, -16.9660728 13.8871792, -16.9663182 13.8836266, -16.9664991 13.8800704, -16.9665735 13.8782914, -16.9668185 13.870801, -16.9668586 13.8691526, -16.9669111 13.8658553, -16.9669235 13.8642497, -16.9668952 13.861934, -16.966786 13.8573902, -16.9665717 13.85285, -16.9662481 13.8482648, -16.9665093 13.8442046, -16.9667012 13.8398236, -16.9667952 13.8354396, -16.9668178 13.8332902, -16.9667914 13.8310546, -16.9666896 13.8266707, -16.9664901 13.8222901, -16.9661928 13.8179147, -16.9657979 13.8135467, -16.9653056 13.8091882, -16.9647161 13.8048412, -16.9641169 13.8010576, -16.9639936 13.7983992, -16.9636951 13.794051, -16.9633003 13.7897101, -16.9628093 13.7853787, -16.9622224 13.7810586, -16.9615398 13.776752, -16.9611822 13.7746441, -16.9607592 13.7724476, -16.9598802 13.7681476, -16.9589056 13.7638673, -16.9578357 13.7596088, -16.9566711 13.7553742, -16.9554122 13.7511654, -16.9540598 13.7469844, -16.9526145 13.7428332, -16.9518828 13.7408033, -16.9512618 13.7391811, -16.950021 13.7360227, -16.948726 13.7328853, -16.9473772 13.7297696, -16.9466894 13.7282173, -16.9441141 13.7225363, -16.942964 13.7200883, -16.9405972 13.7152233, -16.938098 13.710422, -16.9354681 13.7056879, -16.9341399 13.7033703, -16.932977 13.7014521, -16.9306475 13.697705, -16.9282351 13.6940084, -16.9257409 13.6903641, -16.923166 13.6867738, -16.9205117 13.6832393, -16.9177793 13.6797622, -16.91497 13.6763442, -16.9135679 13.6746754, -16.9120852 13.6729869, -16.9091263 13.6696919, -16.9060946 13.6664608, -16.9040883 13.6644138, -16.900064 13.6566535, -16.8960163 13.648848, -16.8919686 13.6410426, -16.887921 13.6332371, -16.8838733 13.6254316, -16.8798256 13.6176261, -16.8757779 13.6098206, -16.8717303 13.6020152, -16.8676826 13.5942097, -16.8672281 13.5933333, -16.5548576 13.5933333, -16.5465852 13.5933333, -16.5449739 13.5933333, -16.5430126 13.5933333, -16.5409006 13.5933333, -16.5304575 13.5933124, -16.5160886 13.5933333, -16.507626 13.5933333, -16.4603013 13.5933333, -16.4273992 13.5933333, -16.4255304 13.5915944, -16.4231665 13.591706, -16.4220965 13.5917086, -16.4206113 13.591637, -16.4187837 13.591691, -16.4163622 13.5916676, -16.4153019 13.5917596, -16.4139067 13.5921395, -16.4118719 13.5925665, -16.4099009 13.5933333, -16.3065434 13.5933333, -16.177804 13.5933333, -16.0851434 13.5933333, -15.9891414 13.5933333, -15.9066462 13.5933333, -15.849924 13.5933333, -15.7545419 13.5933333, -15.6146644 13.5933333, -15.611519 13.5919648, -15.6056997 13.5913647, -15.6055488 13.5913597, -15.6047116 13.5912994, -15.5849219 13.5933333, -15.4760943 13.5933333, -15.4760328 13.5937772, -15.4743998 13.6005305, -15.4743814 13.6006132, -15.4727111 13.6081282, -15.4707799 13.6157132, -15.4684496 13.6208392, -15.4661408 13.6263613, -15.4636174 13.6308365, -15.4622741 13.6356994, -15.4610639 13.6457002, -15.4587036 13.6547582, -15.4558583 13.6639325, -15.4520817 13.6742032, -15.4478975 13.6829264, -15.4435029 13.6933839, -15.4369541 13.7048999, -15.4327484 13.711008, -15.4249635 13.7205178, -15.4186045 13.7332783, -15.4172205 13.7357368, -15.4156101 13.7381141, -15.4141134 13.7401453, -15.4118003 13.7427653, -15.4096835 13.7447048, -15.4012549 13.7526251, -15.3922577 13.7572653, -15.3844986 13.765677, -15.3817156 13.768062, -15.3772416 13.771896, -15.372778 13.775556, -15.368611 13.778333, -15.364444 13.781389, -15.359722 13.783611, -15.355 13.785833, -15.35 13.788056, -15.342696 13.7907362, -15.3363102 13.7919907, -15.3288687 13.7925325, -15.3229229 13.7925863, -15.3210409 13.7926033, -15.3136466 13.792024, -15.3076342 13.7909862, -15.3023299 13.7893274, -15.2950729 13.7863641, -15.2905067 13.784351, -15.2854384 13.7814667, -15.2796405 13.7772987, -15.2755636 13.7727596, -15.2723234 13.7675786, -15.2698301 13.7610135, -15.2665513 13.7510843, -15.2649855 13.7409744, -15.2415665 13.7463351, -15.2413758 13.7463788, -15.2407509 13.7465218, -15.2056122 13.754565, -15.1807825 13.7694242, -15.1552116 13.7817459, -15.1502941 13.7841962, -15.148637 13.7849105, -15.1475234 13.7853616, -15.1454656 13.7862286, -15.1438026 13.7871351, -15.1425688 13.7879228, -15.141586 13.7889523, -15.131811 13.8021859, -15.130987 13.8032663, -15.1298186 13.8043541, -15.1286889 13.8052449, -15.1263124 13.806542, -15.1232955 13.8076881, -15.114772 13.8108691, -15.1113693 13.812139, -15.1062505 13.8140014, -15.094167 13.817778, -15.076667 13.824167, -15.0738216 13.8249668, -15.0719247 13.8252554, -15.0702897 13.8253137, -15.0688702 13.8252481, -15.067086 13.8248481, -15.052222 13.819444, -15.034444 13.8125, -15.025081 13.8086107, -15.016389 13.805, -14.998333 13.798333, -14.9938959 13.7961145, -14.991667 13.795, -14.985752 13.7937548, -14.979583 13.7935902, -14.9749223 13.7934568, -14.970015 13.7937194, -14.9690274 13.7941518, -14.9595823 13.7982872, -14.950304 13.802359, -14.9456712 13.8040448, -14.9434547 13.804723, -14.9414151 13.8051586, -14.9395837 13.8054055, -14.9378499 13.8054732, -14.9336453 13.8051992, -14.927194 13.8047022, -14.9231257 13.8042177, -14.9194768 13.8038541, -14.914444 13.803056, -14.9088982 13.8019641, -14.903056 13.800556, -14.898056 13.798889, -14.893056 13.796944, -14.888056 13.795, -14.883056 13.793056, -14.878611 13.790556, -14.8743558 13.7886048, -14.869167 13.786111, -14.8651655 13.7839055, -14.8622709 13.7821071, -14.8586102 13.7797542, -14.8550461 13.7773451, -14.8515849 13.7753861, -14.847778 13.7725, -14.843889 13.769722, -14.84 13.766389, -14.836111 13.763333, -14.8325 13.76, -14.828889 13.756667, -14.825278 13.753333, -14.8218277 13.749594, -14.8185618 13.7449981, -14.8159011 13.740052, -14.813889 13.736389, -14.811389 13.731667, -14.809444 13.726944, -14.8069339 13.7212857, -14.804713 13.7163891, -14.8031659 13.7118676, -14.801389 13.706667, -14.799444 13.701111, -14.798056 13.695833, -14.797222 13.689722, -14.795278 13.684167, -14.793611 13.678611, -14.793333 13.671667, -14.7925 13.665556, -14.792222 13.658889, -14.791944 13.653333, -14.773889 13.643611, -14.755556 13.633333, -14.7375 13.623056, -14.7347862 13.6214695, -14.719444 13.6125, -14.718611 13.611944, -14.714444 13.614722, -14.711111 13.618333, -14.707778 13.621944, -14.704444 13.625556, -14.700833 13.629167, -14.696667 13.632222, -14.6875945 13.6369813, -14.6749602 13.6421027, -14.6639739 13.6457142, -14.652567 13.6481998, -14.6424215 13.6512904, -14.6400271 13.6520198, -14.6296158 13.6547055, -14.6222001 13.6559565, -14.6113339 13.6575329, -14.604579 13.6580166, -14.5969744 13.6582501, -14.5891638 13.6582668, -14.5813961 13.6582001, -14.5735426 13.6579332, -14.5649853 13.6570554, -14.5572949 13.6557981, -14.5496216 13.6543385, -14.5426221 13.6526412, -14.5355883 13.6504017, -14.5302325 13.6479162, -14.5245676 13.6445882, -14.5198899 13.6412102, -14.513341 13.6364891, -14.5086203 13.6319682, -14.505 13.628333, -14.501389 13.625, -14.4975481 13.6208407, -14.495278 13.616944, -14.4925 13.613056, -14.49 13.608333, -14.487778 13.603611, -14.485278 13.598889, -14.483056 13.593889, -14.481389 13.588611, -14.480556 13.5825, -14.478889 13.576944, -14.477778 13.570833, -14.476944 13.564722, -14.475833 13.558333, -14.475 13.552222, -14.474167 13.546111, -14.4733998 13.5418913, -14.473056 13.54, -14.4720655 13.5348432, -14.466944 13.533333, -14.461389 13.532222, -14.455833 13.530833, -14.4488473 13.5275458, -14.446389 13.526389, -14.4462133 13.5261654, -14.443333 13.5225, -14.440833 13.517778, -14.438056 13.513611, -14.435 13.509722, -14.431389 13.506389, -14.427778 13.503056, -14.424167 13.499722, -14.418889 13.497778, -14.415278 13.494444, -14.410833 13.491944, -14.406389 13.489444, -14.402222 13.486667, -14.398333 13.483333, -14.394167 13.480833, -14.39 13.478333, -14.385556 13.475556, -14.381111 13.473056, -14.3793828 13.4722162, -14.3773055 13.4718999, -14.376667 13.470278, -14.372222 13.467778, -14.3675 13.465833, -14.363056 13.463333, -14.357778 13.461389, -14.353056 13.459722, -14.347778 13.457778, -14.342778 13.455833, -14.337778 13.453889, -14.331944 13.454167, -14.3309586 13.4546597, -14.3275 13.456389, -14.3263492 13.4569004, -14.3225 13.458611, -14.316944 13.460278, -14.3144901 13.461014, -14.311389 13.461944, -14.305556 13.463333, -14.3 13.465, -14.294444 13.466667, -14.289444 13.468889, -14.284722 13.471111, -14.279722 13.473333, -14.273333 13.474167, -14.267222 13.475278, -14.261389 13.476667, -14.255 13.477778, -14.248056 13.478056, -14.240833 13.478333, -14.2389723 13.4796622, -14.236944 13.481111, -14.233333 13.484722, -14.230833 13.488889, -14.228056 13.493056, -14.224722 13.496667, -14.221111 13.500278, -14.217778 13.503889, -14.2137646 13.506796, -14.209444 13.509722, -14.2048758 13.5125315, -14.200556 13.514722, -14.195556 13.517222, -14.192484 13.5182846, -14.1863611 13.5197304, -14.1806052 13.5206156, -14.1805513 13.5206239, -14.1804408 13.5206409, -14.1804194 13.5206442, -14.1789471 13.5208864, -14.1786863 13.5209293, -14.1765555 13.5212799, -14.1747138 13.5222475, -14.173553 13.5238561, -14.1704845 13.5267101, -14.1677422 13.5281058, -14.1637189 13.5294618, -14.1581442 13.5306572, -14.1525502 13.5312163, -14.1460142 13.5309472, -14.1398086 13.5307907, -14.133056 13.533889, -14.126667 13.534722, -14.123889 13.535556, -14.123333 13.535556, -14.120556 13.538333, -14.117222 13.541944, -14.116556 13.542529, -14.1139913 13.5444289, -14.1115618 13.5457557, -14.1066565 13.548042, -14.1030355 13.5493719, -14.1005561 13.5506227, -14.0951252 13.5536232, -14.0893509 13.5560701, -14.084229 13.5586483, -14.0804395 13.5600856, -14.0750108 13.5614894, -14.0705543 13.5630589, -14.0647203 13.5633359, -14.0574983 13.5636139, -14.0513873 13.5630589, -14.0455543 13.5619469, -14.0405543 13.5600029, -14.0352763 13.5580589, -14.0305543 13.5561139, -14.0263873 13.5577809, -14.0222203 13.5605589, -14.0188873 13.5641699, -14.0147203 13.5669469, -14.0105543 13.5700029, -14.0063873 13.5730589, -14.0022203 13.5758359, -13.9972203 13.5780589, -13.9930543 13.5808359, -13.9874983 13.5825029, -13.9805543 13.5827809, -13.9733313 13.5830589, -13.9683313 13.5811139, -13.9630543 13.5791699, -13.9588873 13.5766699, -13.9547203 13.5741699, -13.9508313 13.5708359, -13.9444423 13.5702809, -13.9380543 13.5697249, -13.932068 13.5699553, -13.9308313 13.5700029, -13.9263442 13.5698077, -13.9244423 13.5697249, -13.9238215 13.5695697, -13.9188873 13.5683359, -13.9138873 13.5666699, -13.9094423 13.5638919, -13.908995 13.5636402, -13.9049983 13.5613919, -13.9005543 13.5586139, -13.8997604 13.5579424, -13.8969423 13.5555589, -13.8933313 13.5522249, -13.8897203 13.5488919, -13.8895223 13.5487091, -13.8884307 13.5478364, -13.8861093 13.5455589, -13.8830543 13.5413919, -13.8808313 13.5366699, -13.8783313 13.5319469, -13.8769423 13.5263919, -13.8752763 13.5211139, -13.8736093 13.5155589, -13.8705543 13.5113919, -13.8665788 13.507658, -13.866121 13.5073262, -13.8654931 13.5069304, -13.8630493 13.505427, -13.8592436 13.5036165, -13.854722 13.501667, -13.849722 13.5, -13.845278 13.497222, -13.840833 13.494722, -13.8401758 13.4942904, -13.836667 13.491944, -13.833611 13.488056, -13.829722 13.484722, -13.826944 13.480556, -13.824722 13.475833, -13.821667 13.471944, -13.819444 13.467222, -13.817778 13.463056, -13.8164272 13.4610292, -13.815556 13.459722, -13.811667 13.456389, -13.808056 13.453056, -13.805833 13.448333, -13.803333 13.443611, -13.801389 13.438889, -13.799444 13.433333, -13.79939 13.4327018, -13.798889 13.427222, -13.7984371 13.4215777, -13.798333 13.420278, -13.798333 13.413333, -13.797778 13.406667, -13.798333 13.400278, -13.800833 13.389167, -13.802778 13.384444, -13.805556 13.38, -13.808056 13.375833, -13.814167 13.368056, -13.816944 13.363889, -13.820278 13.360278, -13.823611 13.356667, -13.826084 13.3541887, -13.827222 13.353056, -13.830556 13.349444, -13.834722 13.346667, -13.838889 13.343611, -13.8409793 13.3415207, -13.842222 13.340278, -13.846389 13.337222, -13.849722 13.333611, -13.853889 13.330833, -13.858056 13.327778, -13.862222 13.325, -13.86