# Nature Dependant People - Wetlands Data Processing

In [14]:
import pandas as pd
import geopandas as gpd
import json
import os
import numpy as np

In [15]:
gcs_path = "https://storage.googleapis.com/wetlands-gap-map/original_data"
analysis_data_folder = 'NDP'

In [16]:
locations = gpd.read_file(f'{gcs_path}/locations_simplified.geojson')
locations_sahel = locations[locations['type'] == 'global']
locations_countries = locations[locations['type'] == 'admin_region']
print(f'Total locations: {len(locations)}')
print(f'Total Sahel locations: {len(locations_sahel)}')
print(f'Total country locations: {len(locations_countries)}')

Total locations: 2068
Total Sahel locations: 1
Total country locations: 26

## Load NDP composite index data

In [17]:
file_path = f'{gcs_path}/{analysis_data_folder}/NDP_composite.shp'
ndp_data = gpd.read_file(file_path)
ndp_data['name_en'] = ndp_data['name_en'].str.replace('The Gambia', 'Gambia')
ndp_data = ndp_data.merge(locations_countries[['name', 'code']], left_on='name_en', right_on='name', how='left')
ndp_data.drop(columns=['name_x', 'name_y','fid', 'osm_id', 'name_en', 'boundary', 'admin_leve',
       'admin_cent', 'admin_ce_1', 'admin_ce_2', 'label_node', 'label_no_1',
       'label_no_2', 'layer', 'path', 'geometry'],
        inplace=True)
ndp_data.rename(columns={'GID_0': 'code'}, inplace=True)
ndp_data.dropna(subset=['code'], inplace=True)
ndp_data['location_id'] = ndp_data['code'].apply(lambda x: "adminregion_" + x.lower())
ndp_data.drop(columns=['code'], inplace=True)
ndp_data.columns = ndp_data.columns.str.lower().str.replace(' ', '_')
ndp_data.head(3)

   ndp_comp  ndp_water      location_id
0     0.297       0.17  adminregion_gmb
2     0.386       0.33  adminregion_mrt
3     0.134       0.19  adminregion_sen

In [18]:
# add sahel as average of all countries
sahel_ndp = {'location_id': 'global_sahel',
              'ndp_comp': round(ndp_data['ndp_comp'].mean(), 3),
              'ndp_water': round(ndp_data['ndp_water'].mean(), 3)}
ndp_data = pd.concat([ndp_data, pd.DataFrame([sahel_ndp])], ignore_index=True)
ndp_data['ndp_comp'] = round(ndp_data['ndp_comp'] * 100, 1)
ndp_data['ndp_water'] = round(ndp_data['ndp_water'] * 100, 1)
ndp_data.tail()

    ndp_comp  ndp_water      location_id
22      48.2       40.0  adminregion_cmr
23       0.0        0.0  adminregion_eri
24      73.5       38.0  adminregion_ssd
25      80.2       51.0  adminregion_tcd
26      47.4       37.3     global_sahel

## Export composite index data

In [19]:
indicator_data_list = []

for location in ndp_data['location_id'].unique():
    df_location = ndp_data[ndp_data['location_id'] == location]
    df_location.reset_index(drop=True, inplace=True)
    data_list = []
    for i in range(len(df_location)):
        data_list.append({
            "id":"ndp_composite_" + location + "_" + str(i),
            "label": "ndp_composite",
            "value": df_location.loc[i, 'ndp_comp'],
            "type":"",
            "group": "",
            "color":"#8377FF",
            "format": "percentage",
            "unit": "%"
        })
    data_json = json.dumps(data_list, indent=2)
    temp_dict = {"id": "ndp-composite-" + location,
                 "location": location,
                 "indicator": "ndp-composite",
                 "data": json.loads(data_json),
                 "locale": {"en": {"labels":{
                     "ndp_composite": "NDP composite index",
                    }
                    }},
                }
    indicator_data_list.append(temp_dict)

In [20]:
print(json.dumps(indicator_data_list, indent=2))

[
  {
    "id": "ndp-composite-adminregion_gmb",
    "location": "adminregion_gmb",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_gmb_0",
        "label": "ndp_composite",
        "value": 29.7,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_mrt",
    "location": "adminregion_mrt",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_mrt_0",
        "label": "ndp_composite",
        "value": 38.6,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_sen",
    "location": "adminregion_sen",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_sen_0",
        "label": "ndp_composite",
        "value": 13.4,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_gnb",
    "location": "adminregion_gnb",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_gnb_0",
        "label": "ndp_composite",
        "value": 66.9,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_sle",
    "location": "adminregion_sle",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_sle_0",
        "label": "ndp_composite",
        "value": 66.5,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_gin",
    "location": "adminregion_gin",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_gin_0",
        "label": "ndp_composite",
        "value": 52.6,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_civ",
    "location": "adminregion_civ",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_civ_0",
        "label": "ndp_composite",
        "value": 37.2,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_lbr",
    "location": "adminregion_lbr",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_lbr_0",
        "label": "ndp_composite",
        "value": 71.5,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_gha",
    "location": "adminregion_gha",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_gha_0",
        "label": "ndp_composite",
        "value": 17.2,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_tgo",
    "location": "adminregion_tgo",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_tgo_0",
        "label": "ndp_composite",
        "value": 38.4,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_bfa",
    "location": "adminregion_bfa",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_bfa_0",
        "label": "ndp_composite",
        "value": 59.6,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_ben",
    "location": "adminregion_ben",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_ben_0",
        "label": "ndp_composite",
        "value": 36.6,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_mli",
    "location": "adminregion_mli",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_mli_0",
        "label": "ndp_composite",
        "value": 62.5,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_ner",
    "location": "adminregion_ner",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_ner_0",
        "label": "ndp_composite",
        "value": 68.2,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_nga",
    "location": "adminregion_nga",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_nga_0",
        "label": "ndp_composite",
        "value": 19.5,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_sdn",
    "location": "adminregion_sdn",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_sdn_0",
        "label": "ndp_composite",
        "value": 52.5,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_caf",
    "location": "adminregion_caf",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_caf_0",
        "label": "ndp_composite",
        "value": 77.9,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_uga",
    "location": "adminregion_uga",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_uga_0",
        "label": "ndp_composite",
        "value": 63.5,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_ken",
    "location": "adminregion_ken",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_ken_0",
        "label": "ndp_composite",
        "value": 49.9,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_som",
    "location": "adminregion_som",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_som_0",
        "label": "ndp_composite",
        "value": 12.7,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_eth",
    "location": "adminregion_eth",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_eth_0",
        "label": "ndp_composite",
        "value": 66.6,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_dji",
    "location": "adminregion_dji",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_dji_0",
        "label": "ndp_composite",
        "value": 27.8,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_cmr",
    "location": "adminregion_cmr",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_cmr_0",
        "label": "ndp_composite",
        "value": 48.2,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_eri",
    "location": "adminregion_eri",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_eri_0",
        "label": "ndp_composite",
        "value": 0.0,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_ssd",
    "location": "adminregion_ssd",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_ssd_0",
        "label": "ndp_composite",
        "value": 73.5,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-adminregion_tcd",
    "location": "adminregion_tcd",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_adminregion_tcd_0",
        "label": "ndp_composite",
        "value": 80.2,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  },
  {
    "id": "ndp-composite-global_sahel",
    "location": "global_sahel",
    "indicator": "ndp-composite",
    "data": [
      {
        "id": "ndp_composite_global_sahel_0",
        "label": "ndp_composite",
        "value": 47.4,
        "type": "",
        "group": "",
        "color": "#8377FF",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_composite": "NDP composite index"
        }
      }
    }
  }
]

### Save to JSON

In [21]:
seeding_json = json.load(open('../../app-initial-data/indicator-data.json'))
#remove all entries with id that starts with "ndp-composite-" and "ndp_composite_"
seeding_json = [entry for entry in seeding_json if not entry['id'].
                startswith('ndp-composite-') and not entry['id'].
                startswith('ndp_composite_')]

# Append the new data, if id exists update it
existing_ids = {entry['id'] for entry in seeding_json}
for new_entry in indicator_data_list:
    if new_entry['id'] in existing_ids:
        seeding_json = [entry if entry['id'] != new_entry['id'] else new_entry for entry in seeding_json]
    else:
        seeding_json.append(new_entry)  
with open('../../app-initial-data/indicator-data.json', 'w') as f:
    json.dump(seeding_json, f, indent=2)

## Export water index data

In [22]:
indicator_data_list = []

for location in ndp_data['location_id'].unique():
    df_location = ndp_data[ndp_data['location_id'] == location]
    df_location.reset_index(drop=True, inplace=True)
    data_list = []
    for i in range(len(df_location)):
        data_list.append({
            "id":"ndp_water_" + location + "_" + str(i),
            "label": "ndp_water",
            "value": df_location.loc[i, 'ndp_water'],
            "type":"",
            "group": "",
            "color":"#5AC4C6",
            "format": "percentage",
            "unit": "%"
        })
    data_json = json.dumps(data_list, indent=2)
    temp_dict = {"id": "ndp-water-" + location,
                 "location": location,
                 "indicator": "ndp-water",
                 "data": json.loads(data_json),
                 "locale": {"en": {"labels":{
                     "ndp_water": "NDP water index",
                    }
                    }},
                }
    indicator_data_list.append(temp_dict)

In [23]:
print(json.dumps(indicator_data_list, indent=2))

[
  {
    "id": "ndp-water-adminregion_gmb",
    "location": "adminregion_gmb",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_gmb_0",
        "label": "ndp_water",
        "value": 17.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_mrt",
    "location": "adminregion_mrt",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_mrt_0",
        "label": "ndp_water",
        "value": 33.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_sen",
    "location": "adminregion_sen",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_sen_0",
        "label": "ndp_water",
        "value": 19.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_gnb",
    "location": "adminregion_gnb",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_gnb_0",
        "label": "ndp_water",
        "value": 46.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_sle",
    "location": "adminregion_sle",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_sle_0",
        "label": "ndp_water",
        "value": 61.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_gin",
    "location": "adminregion_gin",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_gin_0",
        "label": "ndp_water",
        "value": 35.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_civ",
    "location": "adminregion_civ",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_civ_0",
        "label": "ndp_water",
        "value": 36.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_lbr",
    "location": "adminregion_lbr",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_lbr_0",
        "label": "ndp_water",
        "value": 89.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_gha",
    "location": "adminregion_gha",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_gha_0",
        "label": "ndp_water",
        "value": 16.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_tgo",
    "location": "adminregion_tgo",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_tgo_0",
        "label": "ndp_water",
        "value": 39.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_bfa",
    "location": "adminregion_bfa",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_bfa_0",
        "label": "ndp_water",
        "value": 33.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_ben",
    "location": "adminregion_ben",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_ben_0",
        "label": "ndp_water",
        "value": 33.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_mli",
    "location": "adminregion_mli",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_mli_0",
        "label": "ndp_water",
        "value": 47.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_ner",
    "location": "adminregion_ner",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_ner_0",
        "label": "ndp_water",
        "value": 54.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_nga",
    "location": "adminregion_nga",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_nga_0",
        "label": "ndp_water",
        "value": 39.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_sdn",
    "location": "adminregion_sdn",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_sdn_0",
        "label": "ndp_water",
        "value": 23.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_caf",
    "location": "adminregion_caf",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_caf_0",
        "label": "ndp_water",
        "value": 51.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_uga",
    "location": "adminregion_uga",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_uga_0",
        "label": "ndp_water",
        "value": 37.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_ken",
    "location": "adminregion_ken",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_ken_0",
        "label": "ndp_water",
        "value": 46.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_som",
    "location": "adminregion_som",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_som_0",
        "label": "ndp_water",
        "value": 26.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_eth",
    "location": "adminregion_eth",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_eth_0",
        "label": "ndp_water",
        "value": 53.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_dji",
    "location": "adminregion_dji",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_dji_0",
        "label": "ndp_water",
        "value": 8.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_cmr",
    "location": "adminregion_cmr",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_cmr_0",
        "label": "ndp_water",
        "value": 40.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_eri",
    "location": "adminregion_eri",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_eri_0",
        "label": "ndp_water",
        "value": 0.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_ssd",
    "location": "adminregion_ssd",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_ssd_0",
        "label": "ndp_water",
        "value": 38.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-adminregion_tcd",
    "location": "adminregion_tcd",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_adminregion_tcd_0",
        "label": "ndp_water",
        "value": 51.0,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  },
  {
    "id": "ndp-water-global_sahel",
    "location": "global_sahel",
    "indicator": "ndp-water",
    "data": [
      {
        "id": "ndp_water_global_sahel_0",
        "label": "ndp_water",
        "value": 37.3,
        "type": "",
        "group": "",
        "color": "#5AC4C6",
        "format": "percentage",
        "unit": "%"
      }
    ],
    "locale": {
      "en": {
        "labels": {
          "ndp_water": "NDP water index"
        }
      }
    }
  }
]

In [24]:
seeding_json = json.load(open('../../app-initial-data/indicator-data.json'))
#remove all entries with id that starts with "ndp-water-" and "ndp_water_"
seeding_json = [entry for entry in seeding_json if not entry['id'].
                startswith('ndp-water-') and not entry['id'].
                startswith('ndp_water_')]

# Append the new data, if id exists update it
existing_ids = {entry['id'] for entry in seeding_json}
for new_entry in indicator_data_list:
    if new_entry['id'] in existing_ids:
        seeding_json = [entry if entry['id'] != new_entry['id'] else new_entry for entry in seeding_json]
    else:
        seeding_json.append(new_entry)  
with open('../../app-initial-data/indicator-data.json', 'w') as f:
    json.dump(seeding_json, f, indent=2)